#threads
BLITZ_NUM_THREADS := 16

#alignment
BLITZ_ALIGNMENT_SIZE := 64

#release, performance
BLITZ_MODE := release

#avx mode 1|2|3|512
BLITZ_AVX := 1

#mkl, atlas
BLAS := mkl

#icc, g++
CC := icc

#link
STATIC_LINK := 0

#GPU
BLITZ_USE_GPU := 0

#MIC
BLITZ_USE_MIC := 0

#cuda architecture
CUDA_ARCH := -arch sm_35
