#threads
BLITZ_NUM_THREADS := 16

#alignment
BLITZ_ALIGNMENT_SIZE := 32

#release, performance, develop
BLITZ_MODE := performance

#avx mode
BLITZ_AVX := 1

#mkl, atlas
BLAS := mkl

#icc, g++
CC := g++

#link
STATIC_LINK := 0

#cpu only
CPU_ONLY := 0

#cuda architecture
CUDA_ARCH := -gencode arch=compute_20,code=sm_20 \
  -gencode arch=compute_20,code=sm_21 \
  -gencode arch=compute_30,code=sm_30 \
  -gencode arch=compute_35,code=sm_35 \
  -gencode arch=compute_50,code=sm_50 \
  -gencode arch=compute_50,code=compute_50
