#icc, g++
CC := g++

#lib only
LIB_ONLY := 1

#alignment
ALIGNMENT_SIZE := 32

#release, performance, develop
MODE := release

#avx mode 0|1|2|3|512
AVX := 1

#mkl, atlas, openblas
BLAS := openblas

#GPU
USE_GPU := 0

#cuda architecture
CUDA_ARCH := sm_35
