#ifndef INCLUDE_UTIL_BLITZ_DEFINE_H_
#define INCLUDE_UTIL_BLITZ_DEFINE_H_

namespace blitz {

enum BLITZ_ALGORITHM {
  BLITZ_CONVOLUTION_SASS_GEMM = 0,
  BLITZ_CONVOLUTION_SASS_DIRECT = 1,
  BLITZ_CONVOLUTION_CUDNN = 2,
  BLITZ_CONVOLUTION_BLAS_GEMM = 3,
  BLITZ_CONVOLUTION_BLAS_GEMM_BATCH = 4,
  BLITZ_CONVOLUTION_XSMM_DIRECT = 5,
  BLITZ_CONVOLUTION_NAIVE_DIRECT = 6,
  BLITZ_CONVOLUTION_VECTOR_DIRECT = 7,
  BLITZ_BLAS_GEMM = 8,
  BLITZ_SASS_GEMM = 9,
  BLITZ_ALGORITHM_UNDEFINED = 10
};

enum BLITZ_DATA_LAYOUT {
  BLITZ_FLAT = 0,
  BLITZ_BUFFER_NCHW = 1,
  BLITZ_BUFFER_NHWC = 2,
  BLITZ_FILTER_KCRS = 3,
  BLITZ_FILTER_RSCK = 4,
  BLITZ_UNPACK_PQRSC = 5,
  BLITZ_UNPACK_PQCRS = 6,
  BLITZ_UNPACK_CRSPQ = 7,
  BLITZ_UNPACK_RSCPQ = 8,
  BLITZ_SHAPE_UNDEFINED = 9
};


}  // namespace blitz

#endif  // INCLUDE_UTIL_BLITZ_ALGORITHM_FUNCTION_H_

